language: go
sudo: false
go:
  - "1.12.x"
env:
  global:
    - GO111MODULE=on
install: true
script:
  - go test -race -coverprofile=coverage.out
after_success:
  - bash <(curl -s https://codecov.io/bash)

